auto-update: false
blazing_apple_heat: 60
blazing_soup_heat: 300
fire_upgrade_cost: 10
fire_upgrade:
  - BLAZE:20
  - MAGMA_CUBE:6
lava_upgrade_cost: 20
lava_upgrade:
  - MAGMA_CUBE:15
fireball_upgrade_cost: 25
fireball_upgrade:
  - BLAZE:20
  - GHAST:6
fire_res_upgrade_cost: 3
fire_res_upgrade:
  - STRIDER:16