name: ThermalFun
version: '${version}'
main: com.github.mmm1245.thermalfun.ThermalFunMain
api-version: 1.18
authors: [ mmm1245 ]
description: SlimeFun addon for addonjam 2022
depend:
  - Slimefun
commands:
  heat:
    description: Sets your heat values
    usage: /<command> <set/add/max> <value>
  thermalAbilities:
    description: Manages your abilities
    usage: /<command> <learn/revoke> <ability>